## 練習2


---

このノートブックの目的はpythonの基本的な使い方の理解です

順番にコードを実行して、Pythonの使い方を確認しましょう

このノートブックでは`docs/Pythonの基本的な使い方.md`をベースにして説明します

練習1では`docs/Pythonの基本的な使い方.md`の`2. Numpy(1次元配列)`から`4. Numpy(その他)`までを扱います

---


### 2. Numpy(1次元配列)

#### 2.1. np.ndarray

ベクトルの和と内積を求めるために、Numpyのnp.ndarrayというN次元配列にPythonのリストをnp.array()で変換します

In [1]:
import numpy as np
from numpy import random

In [3]:
a = [1, 2, 3, 4, 5, 6]
b = [7, 8, 9, 10, 11, 12]

a = np.array(a)
b = np.array(b)
print("和:", a+b)
print("内積:", np.dot(a, b))

和: [ 8 10 12 14 16 18]
内積: 217


四則演算は行列の各要素について行われます

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([7, 8, 9, 10, 11, 12])

print("和: ", a + b) #ベクトルの和

print("差: ", a - b) #ベクトルの差

print("積: ", a * b) #アダマール積

print("商: ", a / b) #ベクトルの各要素の商

print("累乗:", a**2) #a^2

和:  [ 8 10 12 14 16 18]
差:  [-6 -6 -6 -6 -6 -6]
積:  [ 7 16 27 40 55 72]
商:  [0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]
累乗: [ 1  4  9 16 25 36]


条件演算も同様に各要素で演算され配列として返されます

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([1, 3, 3, 3, 5, 5])

print("a==a: ", a==a)

print("a==b: ", a==b)

print("a>b: ", a>b)

a==a:  [ True  True  True  True  True  True]
a==b:  [ True False  True False  True False]
a>b:  [False False False  True False  True]


sin(), log(), exp()なども同様に演算されます

In [6]:
print("sin: ", np.sin(a))

print("log: ", np.log(a))

print("exp: ", np.exp(a))

sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
log:  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
exp:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


max(), sum(), mean(), std()は全体に対して一つの値を返します

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([1, 3, 3, 3, 5, 5])

print("max: ", np.max(a)) # 最大値

print("sum: ", np.sum(a)) # 合計値

print("mean: ", np.mean(a)) # 平均値

print("std: ", np.std(a)) # 標準偏差

max:  6
sum:  21
mean:  3.5
std:  1.707825127659933


二項演算では長さや次元が違う場合、長さを揃えて計算されます

In [8]:
print("3a = ", 3*a)

3a =  [ 3  6  9 12 15 18]


配列aとbの結合は次のように行われます

In [9]:
print("aとbの連結: ", np.r_[a, b])

aとbの連結:  [1 2 3 4 5 6 1 3 3 3 5 5]


pythonのリストに変換するにはlist()を使います

In [10]:
print(a)

print(list(a))

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


#### 2.2. インデックス

`[]`を使うことで任意の位置の値を取得できます

aの後ろから1番目の要素は`a[-1]`で取得できます

In [14]:
print("前から 4 番目の値は a[3] =", a[3])

print("後ろから 4 番目の値は a[-4] =", a[-4])

print("前から 1, 2, 4 番目は", a[[0, 1, 3]])

前から 4 番目の値は a[3] = 4
後ろから 4 番目の値は a[-4] = 3
前から 1, 2, 4 番目は [1 2 4]


`start: end: step`で初項start,公差stepの等差数列で終項はend未満最大の数になるようにスライシングできます

省略も可能です

In [17]:
a = list(range(20)) # 0~19を要素にもつlist
print(a)

print(a[2: 15: 3])

print(a[: 15: 3])

print(a[2: : 3])

print(a[2: 15])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[2, 5, 8, 11, 14]
[0, 3, 6, 9, 12]
[2, 5, 8, 11, 14, 17]
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


Numpyでは1次元配列に対してブールインデックス参照が可能です

In [19]:
a = np.array([1, 3, 5, 7, 9, 11, 13, 15])
bidx = [True, True, False, True, False, True, False, False]

print(a[bidx])

print(a[a % 5 == 0])

[ 1  3  7 11]
[ 5 15]


### 3. Numpy(2次元配列)

#### 3.1. 行列の作成

縦にn行、横にm列の行列を作成する場合もnp.array()を用いる。`a.shape`で配列aの形を確認できます

In [20]:
a = np.array(
    [[1, 2],
    [3, 4],
    [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


`np.ndarray.reshape()`を使うことで、1次元の配列を2次元に整形して行列を作成することもできます

引数に変形後の形を渡す。shapeの引数のうち一つを`-1`とすると自動で整形されます

In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
a1 = a.reshape(3, 2)
print(a1)

a2 = a.reshape(3, -1)
print(a2)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


四則演算は1次元の時と同様に行うことができます

In [23]:
a = np.array([1, 2, 3, 4, 5, 6]).reshape(3, -1)
b = np.array([7, 8, 9, 10, 11, 12]).reshape(3, -1)

print("和: ", a + b) #ベクトルの和

print("差: ", a - b) #ベクトルの差

print("積: ", a * b) #アダマール積

print("商: ", a / b) #ベクトルの各要素の商

print("累乗:", a**2) # 累乗

和:  [[ 8 10]
 [12 14]
 [16 18]]
差:  [[-6 -6]
 [-6 -6]
 [-6 -6]]
積:  [[ 7 16]
 [27 40]
 [55 72]]
商:  [[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]
累乗: [[ 1  4]
 [ 9 16]
 [25 36]]


sin(),log(),exp()などは1次元の時と同様に各要素で演算され配列として返ります

In [24]:
print("sin: ", np.sin(a))

print("log: ", np.log(a))

print("exp: ", np.exp(a))

sin:  [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]
log:  [[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]]
exp:  [[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]


#### 3.2. axis(軸)

2次元配列の縦軸を`axis 0`、横軸を`axis 1`と呼び、np.mean(),np.max()などの集約関数ではaxisを指定することでaxisごとの演算結果を得られます

In [27]:
a = np.array([29, 37, 45, 56, 63, 74, 87, 91, 98, 102, 115, 120]).reshape(4, 3)
print(a)
print(np.max(a))
print("axis 0: ", np.max(a, axis=0))
print("axis 1: ", np.max(a, axis=1))

[[ 29  37  45]
 [ 56  63  74]
 [ 87  91  98]
 [102 115 120]]
120
axis 0:  [102 115 120]
axis 1:  [ 45  74  98 120]


In [28]:
# keepdimsをTrueにすると2次元配列のまま返り値が得られる
print("axis 0: ", np.max(a, axis=0, keepdims=True))

print("axis 1: ", np.max(a, axis=1, keepdims=True))

axis 0:  [[102 115 120]]
axis 1:  [[ 45]
 [ 74]
 [ 98]
 [120]]


NumpyではIndexを`a[axis0,axis1]`のように1つの`[]`で書くことができます

In [30]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(3, 4)
print(a)

# 0行目を取得
print(a[0])

# (0, 1)成分を取得
print(a[0][1])

print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
2
2


In [31]:
# axis 0の0番目と2番目を取得
print(a[[0, 2]]) # a[0, 2]とは違う

# axis 1の0番目と2番目を取得
print(a[:, [0, 2]])

# axis 0に指定するListや配列はaxis 0と同じ向き(縦向き)にする
print(a[[[0], [2]], [[1, 3]]])

# a[0, 1], a[2, 3]を取得
print(a[[0, 2], [1, 3]])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 2  4]
 [10 12]]
[ 2 12]


`np.ix_()`を使うと`a[[[0], [2]], [[1, 3]]]`のような読みにくい構造を簡単に表せます

In [32]:
idx = np.ix_([0, 2], [1, 3])
print(a[idx])

[[ 2  4]
 [10 12]]


2次元配列もスライシング可能です

In [33]:
# aの0行目から1行目までを取り出す
print(a[0:2])

# aの0列目から2列目までを取り出す
print(a[:, 0: 3])

# aの0行目から1行目かつ0列目から2列目を取り出す
print(a[0: 2, 0: 3])

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[1 2 3]
 [5 6 7]]


2次元配列でもindexが同じshapeであれば、ブールインデックス参照できます

In [36]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(2, 4)

print(a)

idx = a%3 == 0 # aのうち3の倍数である値を抜き出す

print(idx)

print(a[idx])

[[1 2 3 4]
 [5 6 7 8]]
[[False False  True False]
 [False  True False False]]
[3 6]


In [37]:
# axis 1にブールインデックスを指定
print(a[:, [False, True, False, True]])

# 2つのaxisにブールインデックスを指定して交差した部分を得る
print(a[np.ix_([True, True], [True, True, False, True])])

[[2 4]
 [6 8]]
[[1 2 4]
 [5 6 8]]


### 4. Numpy(その他)

#### 4.1. 科学定数

Numpyでは$\pi やe$などの科学定数の他に，$\infty$に対応する`np.inf`があります

In [38]:
print("円周率: ", np.pi)

print("ネイピア数: ", np.e)

print("正の無限大: ", np.inf)

print("負の無限大: ", - np.inf)

print(1 + np.inf,1 - np.inf)

円周率:  3.141592653589793
ネイピア数:  2.718281828459045
正の無限大:  inf
負の無限大:  -inf
inf -inf


#### 4.2. 乱数を持つ配列

Numpyには乱数を扱う`random`ライブラリがあります

以下は代表的な例です

- `random.rand()` : [0, 1]上の一様乱数を一つ生成
- `random.randn()` : 標準正規分布(平均0, 分散1)に従う乱数を一つ生成
- `random.normal(mean,std,shape)` : 平均と分散を指定することでその正規分布に従う乱数を生成できるshapeを指定した場合は、正規分布に従う乱数をshapeの数生成する
- `random.randint()` : 整数を乱数として生成する
- `random.seed(seed)` : seedを設定することで生成する乱数を固定できる

In [39]:
from numpy import random

In [41]:
# [0, 1]上の一様乱数を一つ生成
print(random.rand())

0.9781562760275877


In [42]:
# 引数にshapeをかくとそのshapeの一様乱数が生成される
print(random.rand(5)) # 長さ5(=shapeが(5, ) )の1次元配列
print(random.rand(5, 5)) # shapeが(5, 5)の2次元配列　

[0.65120511 0.32443169 0.81100379 0.07888523 0.95031458]
[[0.88873119 0.65601532 0.80011462 0.44752829 0.02725773]
 [0.15833173 0.34062056 0.33639088 0.30655276 0.03166991]
 [0.84337356 0.37930622 0.60104462 0.09834103 0.11581091]
 [0.15454321 0.02220233 0.69644714 0.23273891 0.77998407]
 [0.27046802 0.83167036 0.98963627 0.15382299 0.74142228]]


In [46]:
#rand()ではなくrandn()を使うことで正規分布からサンプリングできる

# 標準正規分布(平均0, 分散1)に従う乱数を一つ生成
print(random.randn())

# 引数にshapeをかくとそのshapeの乱数が生成される
print(random.randn(5)) # 長さ5(=shapeが(5, ) )の1次元配列
print(random.randn(5, 5)) # shapeが(5, 5)の2次元配列　

-1.4786467352427768
[ 1.54508688  0.10399174  2.09497864 -1.0119253  -1.54090928]
[[ 0.85617946 -0.24336313  1.56853385  1.00028349 -0.40391943]
 [-0.6841917  -0.59884627 -0.27229773 -0.60058653 -0.97462209]
 [-2.25526039  0.18699613 -0.1203574   1.67683348  0.39414397]
 [ 0.05527448 -1.68317623 -0.08107892 -0.15282731 -0.82964503]
 [ 1.92495294  0.88813529 -0.32586562 -0.72893929 -0.28571789]]


In [48]:
print(random.normal(100, 10)) # 平均100, 分散10の正規分布に従う乱数
print(random.normal(100, 10, 5)) # 平均100, 分散10の正規分布に従う乱数を5つ持つ1次元配列として作成
print(random.normal(100, 10, (5, 5)))
# 平均100, 分散10の正規分布に従う乱数を値にもつshape (5, 5)の2次元配列として作成

104.67110693801823
[100.85196058  89.1474062   87.45048525  98.62275058  80.60024816]
[[ 94.97048271 100.5026187  114.57862563 107.97214725  83.83401374]
 [105.50698727  98.29979618 104.86974916 118.85518695  92.58295254]
 [ 98.58303522 110.76203878  99.09239213  93.10344749 114.2000617 ]
 [101.73047384  82.88567743 101.98132357 114.7359845   95.96099272]
 [104.42482822  77.59824929  92.77573234  99.38387462  98.98024762]]


In [49]:
print(random.randint(4)) # 0~3の整数を生成
print(random.randint(2, 10, (3, 3))) # 2~9の整数をランダムに値にもつshape (3, 3)の2次元配列を生成

2
[[3 8 9]
 [6 5 6]
 [5 8 7]]


In [50]:
random.seed(seed=32) # seedは任意のint

# 何回実行しても値は同じ
print(random.rand(5))
print(random.randint(2, 10, (3, 3)))

[0.85888927 0.37271115 0.55512878 0.95565655 0.7366696 ]
[[8 3 5]
 [7 4 3]
 [6 5 3]]


#### 4.3. 線形代数の基本的な演算

In [52]:
x = np.arange(1, 4)
y = np.arange(6, 9)
A = np.arange(1, 10).reshape(3, 3)
B = random.randint(1, 10, (3, 3))

print(x)

print(y)

[1 2 3]
[6 7 8]


In [53]:
print(A)

print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6 7]
 [9 5 1]
 [7 5 1]]


`np.transpose()`または`np.ndarray.T`で転置できます

In [54]:
print(np.transpose(A))

print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


内積や行列積は`np.dot()`や`np.matmul()`または`@`を使います

In [55]:
# xとyの内積
print(np.dot(x, y))

print(np.matmul(x, y))

print(x@y)

44
44
44


In [56]:
# AとBの行列積
print(np.dot(A, B))

print(np.matmul(A, B))

print(A@B)

[[ 44  31  12]
 [107  79  39]
 [170 127  66]]
[[ 44  31  12]
 [107  79  39]
 [170 127  66]]
[[ 44  31  12]
 [107  79  39]
 [170 127  66]]


1次元配列は2次元配列として扱う方が扱いやすいことがあります

5次元ベクトルを扱うとき、`shape(5, )`の1次元配列ではなく`shape(5, 1)`の2次元配列とすれば転置などが可能となります

In [59]:
a = np.array([1, 2, 3, 4, 5])

print(a)

[1 2 3 4 5]


In [61]:
# axisが1つしかないので転置前後で変わらない
print(a.T)

[1 2 3 4 5]


In [62]:
# aを横ベクトルの2次元配列にする
a = a.reshape(1, -1)
print(a)

[[1 2 3 4 5]]


In [63]:
print(a.T)

[[1]
 [2]
 [3]
 [4]
 [5]]


#### 4.4. 線形代数計算ライブラリ`linalg`

In [64]:
from numpy import linalg as LA

In [67]:
A = np.arange(1, 10).reshape(3, 3)
B = random.randint(1, 10, (3, 3))

# 行列式を求める
print(LA.det(A))

print(LA.det(B))

-9.51619735392994e-16
-105.99999999999997


In [69]:
# 逆行列を求める
#print(LA.inv(A)) Aは非正則行列のためエラー
print(LA.inv(B))

[[ 0.01886792  0.22641509 -0.35849057]
 [ 0.1509434  -0.18867925  0.13207547]
 [-0.04716981 -0.06603774  0.39622642]]


In [70]:
# ノルムを求める(デフォルトはL2ノルム(ユークリッド距離))
print(LA.norm(A))

print(LA.norm(B))

16.881943016134134
14.866068747318506


In [71]:
# 引数ordを指定するとLpノルムに対応
print(LA.norm(A, ord=1)) # ord=1はマンハッタン距離

print(LA.norm(B, ord=np.inf)) # ordをnp.infにするとL∞ノルム(最大値ノルム)になる

18.0
18.0


うまく実行できたらこのノートブックは終了です

次は`練習3.ipynb`に進みます